#!/bin/sh
set -e

DRAWSCII=$(dirname $0)/../tmp/make/drawscii.*/drawscii
INPUT=$(dirname $0)/input
OUTPUT=$(dirname $0)/output

if [ ! -x $DRAWSCII ]; then
  echo "error: missing drawscii executable" 1>&2
  echo "tried $DRAWSCII"
  exit 1
fi

if [ ! -d $INPUT ]; then
  echo "error: missing input directory" 1>&2
  exit 1
fi

if [ ! -d $OUTPUT ]; then
  echo "error: missing output directory" 1>&2
  exit 1
fi

$DRAWSCII -o $OUTPUT/arrow_vs_text.png   $INPUT/arrow_vs_text.txt
$DRAWSCII -o $OUTPUT/can.png             $INPUT/can.txt
$DRAWSCII -o $OUTPUT/color_codes.png     $INPUT/color_codes.txt
$DRAWSCII -o $OUTPUT/color_more.png      $INPUT/color_more.txt      --no-shadows
$DRAWSCII -o $OUTPUT/corner.png          $INPUT/corner.txt
$DRAWSCII -o $OUTPUT/cornered_line.png   $INPUT/cornered_line.txt
$DRAWSCII -o $OUTPUT/cross.png           $INPUT/cross.txt           --line-width 5
$DRAWSCII -o $OUTPUT/diag_tree.bmp       $INPUT/diag_tree.txt
$DRAWSCII -o $OUTPUT/hell.png            $INPUT/hell.txt            --font-size 20
$DRAWSCII -o $OUTPUT/hell.svg            $INPUT/hell.txt            --font-size 20
$DRAWSCII -o $OUTPUT/intertwined.png     $INPUT/intertwined.txt
$DRAWSCII -o $OUTPUT/letters.png         $INPUT/letters.txt         --background transparent
$DRAWSCII -o $OUTPUT/linked_shapes.png   $INPUT/linked_shapes.txt
$DRAWSCII -o $OUTPUT/rect_intersect.svg  $INPUT/rect_intersect.txt  --shadows
$DRAWSCII -o $OUTPUT/rect_parallel.png   $INPUT/rect_parallel.txt
$DRAWSCII -o $OUTPUT/square_shade.png    $INPUT/square_shade.txt
$DRAWSCII -o $OUTPUT/text_align.png      $INPUT/text_align.txt
$DRAWSCII -o $OUTPUT/text_bg_color.png   $INPUT/text_bg_color.txt
$DRAWSCII -o $OUTPUT/text_separation.png $INPUT/text_separation.txt
$DRAWSCII -o $OUTPUT/turnkey.png         $INPUT/turnkey.txt         --no-antialias
